services:
  moonbunny-host:
    image: ${IMAGE_URL:-ghcr.io/mnbny/moonbunny-host}:${IMAGE_VERSION:-latest}
    ports:
      - '${PORT:-8080}:8080'
    environment:
      DEPLOY_TOKENS: ${DEPLOY_TOKENS:-changeme} # comma-separated
    volumes:
      - '${DATA_PATH:-./data}:/data'
    restart: unless-stopped
